In [ ]:
%pip install numpy

In [7]:
import numpy as np

In [14]:
# 1D array
arr = np.array([10, 20, 30])
arr, arr.ndim, arr.shape, arr.size, arr.itemsize, arr.dtype

(array([10, 20, 30]), 1, (3,), 3, 8, dtype('int64'))

In [16]:
# 2D array
arr2 = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80]
])
arr2, arr2.ndim, arr2.shape, arr2.size, arr2.itemsize, arr2.dtype

(array([[10, 20, 30, 40],
        [50, 60, 70, 80]]),
 2,
 (2, 4),
 8,
 8,
 dtype('int64'))

In [17]:
# 3D array
arr3 = np.array([
    [[10, 20], [30, 40]],
    [[50, 60], [70, 80]]
])
arr3 , arr3.ndim, arr3.shape, arr3.size, arr3.itemsize, arr3.dtype

(array([[[10, 20],
         [30, 40]],
 
        [[50, 60],
         [70, 80]]]),
 3,
 (2, 2, 2),
 8,
 8,
 dtype('int64'))