In [1]:
import numpy as np

In [ ]:
arr = np.eye(3, 3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
arr = np.eye(3, 3, k=1)
arr

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [9]:
arr = np.eye(3,3, k=2)
arr

array([[0., 0., 1.],
       [0., 0., 0.],
       [0., 0., 0.]])